import { Platform, StyleSheet } from 'react-native';
import { ui } from '../../components/mobile-ui';
import { mobileTheme } from '../../constants/mobileTheme';

const theme = mobileTheme;

const styles = StyleSheet.create({
  listContent: { paddingHorizontal: 16, paddingTop: 6, gap: 12 },
  headerStack: { gap: 14, marginBottom: 4 },
  /** When only the error banner is the list header (categories live in hero). */
  listErrorOnly: { marginTop: 2 },
  /** Stack: search + category arc (menu header). */
  heroMenuFooter: {
    width: '100%',
    gap: 12,
  },
  /** Search lives in `MobileGradientHero` footer — white field on gradient. */
  heroSearchRow: {
    width: '100%',
  },
  heroSearchField: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.92)',
    ...Platform.select({
      ios: {
        shadowColor: '#0f172a',
        shadowOpacity: 0.14,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: 5 },
      },
      android: { elevation: 5 },
      default: {},
    }),
  },
  heroSearchInput: {
    flex: 1,
    fontSize: 16,
    paddingVertical: 0,
    minHeight: 22,
    color: theme.colors.text,
  },

  resetText: { color: ui.primary, fontWeight: '700' },

  banner: {
    padding: 12,
    backgroundColor: theme.colors.warningBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.warningBorder,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  bannerText: { flex: 1, color: theme.colors.warningText, fontSize: 13 },
  bannerAction: { color: theme.colors.primaryDeep, fontWeight: '700' },

  itemCard: {
    padding: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.colors.warningBorder,
    backgroundColor: theme.colors.card,
  },
  itemMain: { flexDirection: 'row', gap: 12 },
  imageWrap: { width: 108, position: 'relative' },
  itemImage: { width: 108, height: 108, borderRadius: 16, backgroundColor: theme.colors.border },
  imagePlaceholder: { borderWidth: 1, borderColor: theme.colors.border },
  stateBadge: {
    position: 'absolute',
    left: 6,
    bottom: 6,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  badgeOff: { backgroundColor: 'rgba(127,29,29,0.88)' },
  stateBadgeText: { color: theme.colors.card, fontSize: 10, fontWeight: '800' },
  stateBadgeTextOff: { color: '#fee2e2' },

  itemBody: { flex: 1, minHeight: 108 },
  itemContentTop: { gap: 2 },
  titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 10 },
  itemTitle: { flex: 1, fontSize: 18, lineHeight: 22, fontWeight: '800', color: ui.text },
  infoBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.colors.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.card,
    flexShrink: 0,
    marginTop: 1,
  },
  infoBtnText: { color: '#4b5563', fontSize: 13, fontWeight: '800' },
  itemDesc: { marginTop: 2, fontSize: 14, color: '#4b5563', lineHeight: 19 },
  itemMeta: { marginTop: 4, fontSize: 12, color: theme.colors.muted, fontWeight: '700' },
  itemFooter: { marginTop: 'auto', paddingTop: 8, gap: 2, minHeight: 44, justifyContent: 'center' },
  priceRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  price: { fontSize: 22, fontWeight: '900', color: theme.colors.primaryDeep },
  itemAction: { minWidth: 96, minHeight: 40, paddingHorizontal: 12 },
  unavailablePill: {
    minHeight: 34,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#fecaca',
    backgroundColor: theme.colors.dangerSoft,
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  unavailablePillText: { color: theme.colors.danger, fontSize: 12, fontWeight: '800' },

  emptyCard: {
    marginTop: 8,
    alignItems: 'center',
    paddingVertical: 28,
    paddingHorizontal: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surfaceMuted,
  },
  emptyTitle: { fontSize: 18, fontWeight: '800', color: ui.text },
  emptySub: { marginTop: 6, fontSize: 14, color: ui.subtext },

  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.5)',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
  },
  modalBackdropTouch: { ...StyleSheet.absoluteFillObject },
  /** Full-screen panel: no rounded “card” inset, no border — edge-to-edge. */
  modalSheet: {
    flex: 1,
    flexDirection: 'column',
    width: '100%',
    margin: 0,
    padding: 0,
    overflow: 'hidden',
    borderWidth: 0,
    borderRadius: 0,
    backgroundColor: theme.colors.card,
  },
  modalScrollFlex: {
    flex: 1,
    minHeight: 0,
  },
  modalScrollInner: { paddingBottom: 28, gap: 0 },
  /** Hero flush to screen edges (height set in screen from window %). */
  modalImageWrap: {
    marginHorizontal: 0,
    marginTop: 0,
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 0,
  },
  modalImage: { width: '100%', backgroundColor: theme.colors.border },
  modalImageGradTop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 140,
  },
  modalImageGrad: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 120,
  },
  modalHeroClose: {
    position: 'absolute',
    zIndex: 8,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.55)',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 3 },
      },
      android: { elevation: 6 },
      default: {},
    }),
  },
  modalHero: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 4 },
  modalTitle: { fontSize: 22, fontWeight: '900', color: ui.text, letterSpacing: -0.3 },
  modalMeta: { marginTop: 8, fontSize: 12, color: theme.colors.muted, fontWeight: '700' },
  modalStatRow: { flexDirection: 'row', gap: 14, marginTop: 16 },
  modalStatTile: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 12,
    backgroundColor: theme.colors.surfaceHighlight,
    borderWidth: 1,
    borderColor: `${theme.colors.primary}22`,
  },
  modalStatTileInner: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  modalStatIconOrb: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#f7f3ed',
  },
  modalStatLabel: { fontSize: 10, fontWeight: '800', color: theme.colors.subtext, letterSpacing: 0.4 },
  modalStatValue: { marginTop: 2, fontSize: 14, fontWeight: '800', color: theme.colors.text },
  modalAbout: {
    marginHorizontal: 18,
    marginTop: 20,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: '#f8fafc',
    borderLeftWidth: 4,
    borderLeftColor: theme.colors.primary,
  },
  modalAboutEyebrow: {
    fontSize: 10,
    fontWeight: '800',
    color: theme.colors.primary,
    letterSpacing: 0.9,
    marginBottom: 8,
  },
  modalDesc: { fontSize: 14, color: '#475569', lineHeight: 22, fontWeight: '500' },
  modalLoadingWrap: { paddingVertical: 20, paddingHorizontal: 18 },
  modalSection: { marginHorizontal: 14, marginTop: 10, borderRadius: 14, overflow: 'hidden' },
  modalSectionHead: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingBottom: 0,
  },
  modalSectionIconBg: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  modalSectionTitle: { fontSize: 15, fontWeight: '900', color: theme.colors.text },
  modalSectionSub: { fontSize: 11, color: theme.colors.subtext, fontWeight: '600', marginTop: 2 },
  modalNutCard: {
    paddingVertical: 14,
    paddingHorizontal: 14,
    backgroundColor: '#fffdfb',
    borderWidth: 1,
    borderColor: '#ffedd5',
    borderRadius: 14,
    gap: 10,
  },
  modalNutIconBg: {
    backgroundColor: '#fff7ed',
  },
  modalIngIconBg: {
    backgroundColor: '#ecfdf5',
  },
  modalSectionOuter: { marginHorizontal: 18, marginTop: 22, gap: 12 },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  tagPill: {
    borderWidth: 1,
    borderColor: `${theme.colors.primary}44`,
    backgroundColor: '#fff7ed',
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  tagText: { fontSize: 12, color: theme.colors.primaryDeep, fontWeight: '800' },
  modalIngBody: {
    paddingVertical: 6,
    paddingHorizontal: 4,
    backgroundColor: '#fffaf5',
    borderWidth: 1,
    borderColor: '#fed7aa',
    borderRadius: 14,
    gap: 0,
  },
  modalIngRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 13,
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#fde68a',
  },
  modalIngRowLast: { borderBottomWidth: 0 },
  modalIngBullet: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: theme.colors.primary,
    marginTop: 5,
  },
  modalIngText: { flex: 1, fontSize: 14, color: '#78350f', lineHeight: 22, fontWeight: '600' },
  modalHealthCard: {
    paddingVertical: 14,
    paddingHorizontal: 14,
    backgroundColor: '#ecfdf5',
    borderWidth: 1,
    borderColor: '#a7f3d0',
    borderRadius: 14,
    gap: 12,
  },
  modalHealthRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  modalHealthIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(22,163,74,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalHealthText: { flex: 1, fontSize: 14, color: '#14532d', lineHeight: 22, fontWeight: '600' },
  infoMuted: { fontSize: 13, color: theme.colors.subtext, fontStyle: 'italic' },
  modalFooterBar: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.border,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 12,
    backgroundColor: theme.colors.card,
    gap: 16,
  },
  /** Price + status stacked so the badge is not cramped beside the price. */
  modalFooterSummary: {
    gap: 10,
    alignItems: 'flex-start',
  },
  modalPrice: { fontSize: 28, fontWeight: '900', color: theme.colors.primaryDeep, letterSpacing: -0.5 },
  modalStatusBadge: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignSelf: 'flex-start',
  },
  modalOn: { backgroundColor: 'rgba(22,163,74,0.12)' },
  modalOff: { backgroundColor: 'rgba(185,28,28,0.12)' },
  modalStatusText: { fontSize: 12, fontWeight: '800', color: '#374151' },
  modalPrimaryFull: {
    alignSelf: 'stretch',
    width: '100%',
    minHeight: 52,
    borderRadius: 14,
  },
});

export { styles };
